# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: devconnector CD

on:
    push:
        branches: [main]

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Intall dependecies
              run: npm ci
            - name: Run tests
              run: npm test
            - name: Check formatting
              run: npm run check-format
            - name: Check with linter
              run: npm run linter
