# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: devconnector CD

on:
    push:
        branches: [master]

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Intall dependecies
              run: npm ci
            - uses: expo/expo-github-action@v5
              with:
                  expo-version: 3.x
                  expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
                  expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
            - name: Run tests
              run: npm test
            - name: Check with linter
              run: npm run linter
            - name: Publish on expo
              run: expo publish
